---

- name: performing yum update
  yum:
    name: '*'
    state: latest
    update_cache: yes
  when: |
    ansible_facts.os_family == 'RedHat' and
    ansible_facts.distribution_major_version == '7'

- name: Enable epel-release on Centos 7
  yum:
    name: epel-release
    state: latest
  when: |
    ansible_facts.os_family == 'RedHat' and
    ansible_facts.distribution_major_version == '7'

- name: install packages from a list
  yum:
    name: "{{item}}"
    state: latest
  loop: "{{managed_packages}}"

#- debug:
#    msg: "{{ansible_facts.os_family}} and {{ansible_facts.distribution_major_version}}"

