---
- name: Enable epel-release on Centos 7
  yum:
    name: epel-release
    state: latest
  when: |
    ansible_facts.os_family == 'RedHat' and
    ansible_facts.distribution_major_version == '7'

- name: upgrade all packages
  yum:
    name: *
    state: latest

#- debug:
#    msg: "{{ansible_facts.os_family}} and {{ansible_facts.distribution_major_version}}"

